name: CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  backend:
    name: Backend (Maven)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: Build & Test backend
        working-directory: ./bookify_app
        run: mvn -Ptest verify

  frontend:
    name: Frontend (Vite + Vitest)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        working-directory: ./bookify_app/frontend
        run: npm ci

      - name: Run lint
        working-directory: ./bookify_app/frontend
        run: npm run lint

      - name: Run tests
        working-directory: ./bookify_app/frontend
        run: npm run test -- --run
